FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -U --no-cache-dir \
    hdmf-zarr==0.8.0 \
    neuroconv==0.6.4 \
    pynwb==2.8.2 \
    zarr==2.17.2 \
    spikeinterface[full]==0.101.2 \
    wavpack-numcodecs==0.2.1
