#!/usr/bin/env bash
set -e

pip uninstall -y spikeinterface
git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 1fc89b4a128f4584fc560f963200b076734d2654
pip install --no-cache-dir .[full]
cd ..