#!/usr/bin/env bash
set -e

git clone https://github.com/alejoe91/spikeinterface.git
cd spikeinterface
git checkout 42e1f024aaa0c2af823f715a78d1d95a33807732
pip install --no-cache-dir .[full,widgets]
cd ..


git clone https://github.com/catalystneuro/neuroconv.git
cd neuroconv
git checkout sorting-analyzer
pip install --no-cache-dir .
cd ..
